# Generated by Django 6.1.1 on 2026-09-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('alert_type', models.CharField(choices=[('rain', 'Rain'), ('heat', 'Heat'), ('wind', 'Wind')], max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('advice', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('source', models.CharField(default='prototype-rule-engine', max_length=100)),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'starts_at'], name='alerts_aler_latitud_9bfb7b_idx')],
            },
        ),
    ]
