# Generated by Django 6.1.1 on 2026-09-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_key', 'created_at'], name='locations_s_client__a4b318_idx')],
            },
        ),
    ]
